Update image_processing_pipeline.yml

diff --git a/.github/workflows/image_processing_pipeline.yml b/.github/workflows/image_processing_pipeline.yml
--- a/.github/workflows/image_processing_pipeline.yml
+++ b/.github/workflows/image_processing_pipeline.yml
@@ -49,10 +49,10 @@ jobs:
     # Step 8: Check if the output file exists before committing
     - name: Verify output file exists
       run: |
-      if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
-      echo "Output file not found!"
-      exit 1
-    fi
+        if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
+          echo "Output file not found!"
+          exit 1
+        fi
 
     # Step 9: Commit the final processed output to the repository
     - name: Commit final output
