Update image_processing_pipeline.yml

diff --git a/.github/workflows/image_processing_pipeline.yml b/.github/workflows/image_processing_pipeline.yml
--- a/.github/workflows/image_processing_pipeline.yml
+++ b/.github/workflows/image_processing_pipeline.yml
@@ -46,15 +46,16 @@ jobs:
     - name: Run script3.py
       run: python scripts/script3.py
 
-    # Step 8: Verify if the output file exists
-    - name: Verify output file exists
-      run: |
-        if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
-          echo "Output file not found!"
-          exit 1
-        else
-          echo "Output file found!"
-        fi
+# Step 8: Verify if the output file exists
+- name: Verify output file exists
+  run: |
+    if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
+      echo "Output file not found!"
+      exit 1
+    else
+      echo "Output file found!"
+    fi
+
 
     # Step 9: Commit the final processed output to the repository
     - name: Commit final output
