Update image_processing_pipeline.yml

diff --git a/.github/workflows/image_processing_pipeline.yml b/.github/workflows/image_processing_pipeline.yml
--- a/.github/workflows/image_processing_pipeline.yml
+++ b/.github/workflows/image_processing_pipeline.yml
@@ -46,24 +46,25 @@ jobs:
     - name: Run script3.py
       run: python scripts/script3.py
 
-    # Step 8: Verify if the output file exists
-    - name: Verify output file exists
-      run: |
-        if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
-          echo "Output file not found!"
-          exit 1
-        else
-          echo "Output file found!"
-        fi
+# Step 8: Verify if the output file exists
+- name: Verify output file exists
+  run: |
+    if [ ! -f "process/merged_data_with_metadata.csv" ]; then
+      echo "Output file not found!"
+      exit 1
+    else
+      echo "Output file found!"
+    fi
 
-    # Step 9: Commit the final processed output to the repository
-    - name: Commit final output
-      run: |
-        git config --global user.email "action@github.com"
-        git config --global user.name "GitHub Action"
-        git add decryption/process/merged_data_with_metadata.csv
-        git commit -m "Add processed result"
-        git push
+# Step 9: Commit the final processed output to the repository
+- name: Commit final output
+  run: |
+    git config --global user.email "action@github.com"
+    git config --global user.name "GitHub Action"
+    git add process/merged_data_with_metadata.csv
+    git commit -m "Add processed result"
+    git push
+
 
     # Step 10: Run script4.py to delete PNG files and push changes
     - name: Delete Uploaded PNGs and Push Changes
